"""Tests for the POST /chat stub endpoint.

Requirements:
- platform-scaffold-009: POST /chat returns a valid TurnOutput with all nine contract fields.
- platform-scaffold-010: stub sets needs_review=True + fixed placeholder reply; no LLM call.
"""

from fastapi.testclient import TestClient

from app.api.chat import _PLACEHOLDER_REPLY
from app.contract import TurnOutput
from app.main import app

# The nine canonical TurnOutput field names (non-negotiable per the per-turn JSON contract).
_NINE_FIELDS: frozenset[str] = frozenset(
    {
        "reply",
        "detected_lang",
        "active_lang",
        "lang_confidence",
        "final_normalized_text",
        "detected_country",
        "confidence_score",
        "needs_review",
        "guardrails",
    }
)


def test_chat_stub_returns_200_with_all_nine_fields() -> None:
    """POST /chat returns 200 and a fully-valid TurnOutput with exactly 9 fields.

    # platform-scaffold-009
    """
    with TestClient(app) as client:
        response = client.post(
            "/chat",
            json={"session_id": "test-session-001", "message": "Hola, qué es la filosofía?"},
        )

    assert response.status_code == 200
    data = response.json()
    # Exactly the nine contract fields must be present in the JSON payload.
    assert set(data.keys()) == _NINE_FIELDS  # platform-scaffold-009
    # Body must deserialize to a valid TurnOutput without raising ValidationError.
    output = TurnOutput.model_validate(data)
    assert output is not None


def test_chat_stub_needs_review_true_and_fixed_reply() -> None:
    """Stub sets needs_review=True and emits the fixed placeholder reply (no LLM call).

    No LLM API keys are required for this test to pass, which proves no model is invoked.
    # platform-scaffold-010
    """
    with TestClient(app) as client:
        response = client.post(
            "/chat",
            json={"session_id": "test-session-002", "message": "test message"},
        )

    assert response.status_code == 200
    data = response.json()
    assert data["needs_review"] is True  # platform-scaffold-010
    # Fixed placeholder — not generated by an LLM.
    assert data["reply"] == _PLACEHOLDER_REPLY  # platform-scaffold-010
